Pin ansible-core at 2.14.11
Since the release of ansible-core 2.14.12 and 2.15.7 yesterday, kayobe
fails with the following error in [kolla-openstack : Collect details
about custom config]:

    TypeError: Pattern and root_dir should be of the same type, not <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'> and <class 'str'>

This does not affect stable/2023.1 directly because the failing code is
not present, but it affects master through upgrade jobs where the
ansible-core dependency is kept at 2.14.x.

Change-Id: I5cb458132133d171037f8697072e6bd8858db01a