CI: Fix molecule job on Ubuntu Jammy
OpenDev has changed the image used for tox jobs to Ubuntu Jammy 22.04.
This broke molecule jobs, which started failing with:

ImportError: cannot import name 'Iterable' from 'collections'

This change updates requirements to bump molecule and pytest-metadata.
It also removes molecule flake8 lint configuration, which is no longer
supported.

Change-Id: I751a458f7668f7917abaa662723221ac7e3752c8