Cap paramiko to releases below 2.5.0
This new version makes the kayobe-tox-molecule job fail with:

    ImportError: cannot import name py31compat

Change-Id: Ieddf039483649cc7b575019409257b6ce5b3fb99
(cherry picked from commit 686cf8d5419d20499e824d155232ef23bde4535b)