CI: Fix kayobe-tox-molecule job
When molecule runs, it installs ansible>2.8, which is now version
2.10.1. This now also installs the ansible-base package, currently at
version 2.10.2. Then it installs the version of ansible required by
kayobe, i.e. ansible>=2.5.0,<2.8.0 (currently 2.7.18).

We end up with a tox molecule venv containing:

ansible==2.7.18
ansible-base==2.10.2

This causes the following issue (hidden by default because of no_log):

AttributeError: 'ActionModule' object has no attribute 'get_shell_option'

This commit adds requirements.txt to the molecule tox deps, which
ensures the correct version of ansible gets installed first.

Change-Id: I7ef890a2ae6fd67f53e1b8bca244a1c0d44fea53
(cherry picked from commit c58555498836066002dc33620018e9bd1e2eeb6a)