Fix issue with image download when checksum url is none
TASK [image-download : Ensure the image is downloaded] *************************
task path: /home/zuul/kayobe-venv/share/kayobe/ansible/roles/image-download/tasks/main.yml:19
fatal: [localhost]: FAILED! => {
    "msg": "The field 'vars' has an invalid value, which includes an undefined variable. The error was: 'dict object' has no attribute 'content'\n\nThe error appears to have been in '/home/zuul/kayobe-venv/share/kayobe/ansible/roles/image-download/tasks/main.yml': line 19, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Ensure the image is downloaded\n      ^ here\n"
}
	to retry, use: --limit @/home/zuul/kayobe-venv/share/kayobe/ansible/kolla-openstack.retry

PLAY RECAP *********************************************************************
controller0                : ok=3    changed=0    unreachable=0    failed=0
localhost                  : ok=6    changed=2    unreachable=0    failed=1

Change-Id: I45fb193b423c7e874aa70cd5f0252e0b0f4e2f05
Story: 2006715
Task: 37086
(cherry picked from commit dea36ac9d24c1e8cf19f0d27ee49be657d736da6)