Pin rich to <11 due to breaking ansible-lint in kayobe-tox-molecule
With rich 11+ we see the following issue when linting in the molecule job:

ImportError: cannot import name 'render_group' from 'rich.console'

Change-Id: I65631db4c4fd2a3248cfb182d78f4c71683dc150