Fix installation errors with Python 2
Python 2 jobs recently started failing frequently with the following
error:

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=2.0')

The root cause appears to be that indirect requirements are handled by
easy_install which doesn't like some index servers [1]. Install the
latest setuptools first to work around the issue.

Disable upgrade jobs since the same issue is affecting Kayobe
installation in the previous release (Rocky).

[1] https://github.com/googleapis/google-cloud-python/issues/3757#issuecomment-422384453

Change-Id: I1b86c5f58d0c3b63269766eaa8e76af18b5fadb1