Disable broken linting of literalinclude sphinx directive
Previously we were seeing:

AttributeError: 'Values' object has no attribute 'env'

TrivialFix
Change-Id: I2b376303a9fef8fb3c1ada0c168bbb494216aa94
(cherry picked from commit c96803d8d1974c87e0dca004b4e360d48ee0fe8f)