Restore upper constraints for docs and releasenotes
Without upper constraints, we install the newly released Sphinx 4.0.0,
which breaks with:

Extension error (openstackdocstheme.ext):
Handler <function _builder_inited at 0x7ff877d4f2f0> for event
'builder-inited' threw an exception (exception: make_link_role() missing
1 required positional argument: 'caption')

When using upper constraints, tox fails with:

ERROR: Cannot install cliff<2.15.0 and >=2.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested cliff<2.15.0 and >=2.5.0
    The user requested (constraint) cliff===2.16.0

Stop using requirements.txt to avoid this issue. This is already the
case in stable/victoria and newer branches [1].

[1] https://review.opendev.org/c/openstack/kayobe/+/752686

Change-Id: I469b65e9dd6a52572dc94604bbe1811a07a29c46