CI: Fix libvirt errors caused by latest edk2-ovmf
Some CentOS Stream CI jobs started to fail when defining VMs with:

    libvirt.libvirtError: internal error: unknown feature amd-sev-es

This was introduced by edk2-ovmf-20200602gitca407c7246bf-5.el8.noarch.
This change excludes this package version in Zuul jobs, which fixes the
kayobe-seed-vm-centos8s job.

Overcloud centos8s jobs were also broken by the nova-libvirt Kolla image
containing this package, which is used by Tenks. Updated images using
the previous version of edk2-ovmf [1][2] are now available from quay.io.

This also needs to be fixed for Kayobe and Tenks in general, unless a
new package is released soon.

[1] https://review.opendev.org/c/openstack/kolla/+/792999
[2] https://review.opendev.org/c/openstack/kolla/+/793174

Change-Id: I5bc8197143ce763cdaf8a9ac0b782b524d5df258