CI: fix molecule job
Molecule job failed with an error:
AttributeError: 'Runtime' object has no attribute 'exec'
since 4.x ansible-compat were bring the breaking changes [1].
so we pin the 3.x version for molecule.

1. https://github.com/ansible/ansible-compat/pull/256

Change-Id: I5f0b97fec565036fb48654113d356cc947e1bbb8
Signed-off-by: Maksim Malchuk <maksim.malchuk@gmail.com>