CI: pin pytest-metadata<2 for molecule
The release of pytest-metadata 2.0.0 appears to have broken the molecule tests.

  AttributeError: 'Config' object has no attribute '_metadata'

Change-Id: I60cf89ce2f8c236b7febb92d437abf7e21bb7acd
(cherry picked from commit f3bca3e0f69982ce6c4eac72d1ab95f8732f4feb)