CI: Fix stable/stein jobs
tox jobs are now failing on python dependencies due to the new pip
resolver:

    ERROR: Could not find a version that satisfies the requirement docker<3
    ERROR: No matching distribution found for docker<3

Remove upper limits from docker and paramiko. molecule is only required
for the molecule tox environment, which is Python 2.

Fix extracted from commit ac7adbb9b56cd9901c7a0bfb826f8b60d590a792 on
the stable/train branch.

We disable the kayobe-overcloud-upgrade-centos job which breaks during
overcloud-deploy-pre-upgrade on:

    TASK [prechecks : Checking Docker version] *************************************
    fatal: [controller0]: FAILED! => {"changed": false, "cmd": ["docker", "--version"], "delta": "0:00:00.202792", "end": "2021-03-29 14:44:23.513939", "failed_when_result": true, "rc": 0, "start": "2021-03-29 14:44:23.311147", "stderr": "", "stderr_lines": [], "stdout": "Docker version 20.10.5, build 55c4c88", "stdout_lines": ["Docker version 20.10.5, build 55c4c88"]}
            to retry, use: --limit @/home/zuul/kolla-venv/share/kolla-ansible/ansible/site.retry

Change I2a23eea7effb5b9a5e73361bcd48bd2e16d1569c would need to be
backported to kolla-ansible stable/rocky, but this branch is not
maintained anymore.

Change-Id: Idf144c358c85e0db34a672b86f01e084efbe7947