Fix tox cover environment on python 3.6
In python 3.6, os.path.join does not accept Mock objects, giving the
following error:

TypeError: expected str, bytes or os.PathLike object, not MagicMock

Since the switch to use ubuntu bionic for the base image for jobs,
python 3.6 is the default for python 3.

Change-Id: I79bec585361a54b8303c130a363c62d9a4b7faae
Story: 2004959
Task: 30035