Fix firewalld configuration for monitoring hosts
There was a stray double quote in the firewalld config for monitoring
hosts, resulting in the following error when firewalld is enabled:

  ValueError: No closing quotation

Closes-Bug: 2019867
Change-Id: I201faf14da5d143670250052ab15fc285f24868c
(cherry picked from commit b7e95c83d3ea22bdccb5a5440e677c8a36f4cf61)