Change name of element for diskimage-builder
Error when try to initiate image build ==>
/bifrost-base-source/bifrost-base-archive-stackhpc-pike/playbooks/roles/bifrost-create-dib-image/tasks/main.yml:121
 diskimage_builder.element_dependencies.MissingElementException: Element 'serial-console' not found
 diskimage-builder version 2.9.1

Check on https://docs.openstack.org/diskimage-builder/latest/elements/enable-serial-console/README.html

serial-console => enable-serial-console
(cherry picked from commit 08466ba5d5ae46ad630e6d3a3d02f3591a5eeaaf)

Change-Id: I1393e74fb88cf49df128b002728c219ca75ad0a8