Fix network configure on Rocky hosts
When evaluating the templates, an error is raised failing to load
ipaddr. Fix this by bumping the version of MichaelRigart.interfaces.

```
ansible.errors.AnsibleError: template error while templating string: Could not load "ipaddr": 'ipaddr'.
```

2023.2 only: make host configure jobs non-voting because of failing NTP
checks.

Closes-Bug: #2107335
Change-Id: I17a94a7367c57b37fa01db737f0235472360155a