CI: Fix molecule job failure
The molecule job is failing with this error in rich/_lru_cache.py:

    ImportError: cannot import name 'OrderedDict' from 'typing_extensions'

This followed the release of rich 12.1.0 [1]. Cap rich below this
version.

This commit also separates molecule requirements into their own file.
This is similar to I4cad83c92c32d1db2a5d3c03a78a1c533a8b9633 applied on
the master branch during the Xena cycle, although we keep using upper
constraints for molecule because they work.

It also includes changes from 07eb06755e657684e79dd285a7ef02d5369ea5e1:
pin ansible-lint to <6 and ignore changes to molecule-requirements.txt
for jobs that don't use it.

[1] https://github.com/Textualize/rich/issues/2164

Change-Id: I555702c19acd1cb4c4aa52987cd7991334ae1cd7