Force use of yoga upper constraints in ipa-builder
IPA itself is still compatible with Python 3.6, but ipa-builder uses
master upper-constraints which have dropped support for 3.6 and are
pulling importlib-metadata===4.11.4, which requires 3.7.

    ERROR: Cannot install ironic-python-agent==8.6.1.dev13 because these package versions have conflicting dependencies.

    The conflict is caused by:
        ironic-python-agent 8.6.1.dev13 depends on importlib_metadata>=1.7.0
        The user requested (constraint) importlib-metadata===4.11.4

Change-Id: I0cc48d0d5ed17400badb081e9117c9351677bb38