Ubuntu: Fix networkd config for multiple VLANs without MTU
TypeError: '>' not supported between instances of 'NoneType' and
'NoneType'

Story: 2009013
Task: 42729

Change-Id: I8e25fdc459102ca6e13bd3d38191554ba32c1f48
(cherry picked from commit ead017e1969b70fddabe7390f2727eb0dc34e620)